### ISSUE TITLE
Feature Request - RCS Fuel Use for Momentum Dumping

### ISSUE THREAD

**Issue by Felger** [Crzyrndm/RW-Saturatable#1]
As a difficulty option, instead of naturally recovering CMG torque over time (or in addition to, if you want to "account" for effects like solar pressure, and gravity gradient torque stabilization), present the option to specify a resource to drain to dump CMG / RW momentum and regain torque.  When that resource is depleted, the reaction wheels will either never regain torque, or regain extremely slowly.

**Comment by Crzyrndm** [comment]
If it's just consuming "resourceX" to dump momentum, that's easy enough.

**Comment by Crzyrndm** [comment]
Obviously stock is only going to be one resource, but is a RF/RO interpretation likely to want to consume multiple resources?

**Comment by Felger** [comment]
Yes, RF / RO is going to want a table of resources to draw from. As an
idea, you could scan for parts with moduleRCS\* and grab the Isp and fuel
type from that. Actually, thinking about it, stock might want to use
multiple resources too, with the vernier thrusters.

**Comment by Crzyrndm** [comment]
Don't have enough time to do that and make sure it actually works atm

Added two new fields to the module which can be see here: https://github.com/Crzyrndm/RW-Saturatable/blob/master/GameData/RW%20Saturatable/RW.cfg#L19-L20
Only usable with the github .dll currently

Zero out the bleed rate pct's and it will only recover through resource usage (toggled with a button in the window)

**Comment by Felger** [comment]
That's awesome, and you're awesome!

**Comment by Crzyrndm** [comment]
Finished cleaning up the most glaring issues in yesterdays version (namely uneven resource consumption)

I see a few options wrt to working out what fuels to consume:
1) Search the vessel for RCS(FX) modules and use their propellant combination. The issue here is the player will have no or very little control over which resources are used
2) Add a dummy RCS(FX) module to the part with no thrust (torque set in the RW module) to use for propellant visibility. This gives the player control over fuel flow (related to part position) and displays the resource info to the player in a way that is already understood
3) Retain the current format

If having a zero thrust RCS block doesn't give KSP a headache, that would be my preferred option. Opinion?

**Comment by Felger** [comment]
@NathanKell would be more able to answer this than I.  That being said, if it's a RealFuels configurable dummy RCS block, we can set it up so that it can use any RCS fuel, just that the player will need to set it up to use the same fuel as his RCS thrusters.

It would probably work, though.

As an alternative to zero thrust, if KSP doesn't like it (I suspect you'll get no fuel flow), you could use a model with an invisible texture and symmetric RCS thrust vectors, add it to every reactionwheel part, then fire both thrusters at the same time, cancelling each other's thrust, effectively just burning fuel.

Pretty hacky, but it'd probably work.

**Comment by NathanKell** [comment]
It'll work fine with zero thrust, the only purpose for the RCS block would be to expose the Propellants list.

That does seem to be the best option.

**Comment by Crzyrndm** [comment]
Now a part of release version, using a disabled RCS module to specify fuels to use and rates to use them at. Module is commented out by default for now atleast.

**Comment by Felger** [comment]
Awesome!
